### ISSUE TITLE
colormap function not working with glumpy 1.0.6 and python 3.5

### ISSUE THREAD

**Issue by sachinjm** [glumpy/glumpy#111]
I am having glumpy 1.0.6 with python 3.5. I am facing same error as AttributeError: module 'glumpy' has no attribute 'colormap'. Tried running test_rbm.py from https://github.com/trunghlt/pyRBM and followed instructions from https://github.com/glumpy/glumpy in install glumpy.

Please help me
Sachin

**Comment by rougier** [comment]
Same as #112, I think you're using old examples.

**Comment by sachinjm** [comment]
Same as #112
